backend:
  name: git-gateway
  branch: main # O la rama que uses, por ejemplo 'master'

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Página Principal"
        name: "home"
        fields:
          - {label: "Título del Héroe", name: "hero_title", widget: "string"}
          - {label: "Subtítulo del Héroe", name: "hero_subtitle", widget: "string"}
          # Puedes añadir más campos para los textos de la página de inicio
      - file: "content/about.md"
        label: "Sobre Nosotros"
        name: "about"
        fields:
          - {label: "Título de la Misión", name: "mission_title", widget: "string"}
          - {label: "Misión", name: "mission_text", widget: "text"}
          - {label: "Título de la Visión", name: "vision_title", widget: "string"}
          - {label: "Visión", name: "vision_text", widget: "text"}
      - file: "content/faq.md"
        label: "Preguntas Frecuentes"
        name: "faq"
        fields:
          - {label: "Preguntas Frecuentes", name: "faqs", widget: "list", fields: [
              {label: "Pregunta", name: "pregunta", widget: "string"},
              {label: "Respuesta", name: "respuesta", widget: "text"}
            ]}

  - name: "products"
    label: "Productos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID del Producto", name: "id", widget: "string", required: true}
      - {label: "Nombre del Producto", name: "name", widget: "string", required: true}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Características", name: "features", widget: "list"}
      - {label: "Precio", name: "price", widget: "number", value_type: "float", min: 0}
      - {label: "Precio Original", name: "originalPrice", widget: "number", value_type: "float", min: 0}
      - {label: "Imagen", name: "img", widget: "image", required: true}
      - {label: "Etiqueta (opcional)", name: "badge", widget: "string", required: false}
